Repository Kaus8ubh/Knowledge-Management-frontend, pull requests merged in 2025-04, with the labels that each got.

#3 Add Knowledge Card Component
  package-lock.json
  package.json
  src/components/AddKnowledgeCard.jsx
  src/components/AllKC.jsx
  src/components/KnowledgeCard.jsx
  src/components/Navbar.jsx
  src/css/AddKnowledgeCard.css
  src/css/Home.css
  src/css/KnowledgeCard.css
  src/pages/Home.jsx
  vite.config.js
Labels: feature

#4 Enhanced KC Component
  src/components/AllKC.jsx
  src/css/KnowledgeCard.css
Labels: enhancement

#5 Merging First Milestone from develop branch to Main branch
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/Brieffy_Logo-withoutbg_zoom.png
  public/signInCoverPhoto.jpg
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/components/AddKnowledgeCard.jsx
  src/components/AllKC.jsx
  src/components/KnowledgeCard.jsx
  src/components/Navbar.jsx
  src/components/ProtectedRoute.jsx
  src/context/AuthContext.jsx
  src/context/AuthProvider.jsx
  src/css/AddKnowledgeCard.css
  src/css/Home.css
  src/css/KnowledgeCard.css
  src/css/SignIn.css
  src/hooks/useAuth.js
  src/index.css
  src/main.jsx
  src/pages/Home.jsx
  src/pages/SignIn.jsx
  vite.config.js
Labels: feature

#17 Major Changes
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/AddKnowledgeCard.jsx
  src/components/AllKC.jsx
  src/components/KnowledgeCard.jsx
  src/components/RichTextEditor.jsx
  src/components/SkeletonCard.jsx
  src/css/AddKnowledgeCard.css
  src/css/GoogleButton.css
  src/css/Home.css
  src/css/KnowledgeCard.css
  src/index.css
  src/main.jsx
  src/pages/Home.jsx
  src/pages/SignIn.jsx
  src/pages/Suites.jsx
  src/services/KnowledgeCardService.js
  vite.config.js
Labels: enhancement, feature

#21 Fixed CSS for AllKC and Expanded KC View and Add KC pop up
  src/components/AddKnowledgeCard.jsx
  src/components/AllKC.jsx
  src/components/KnowledgeCard.jsx
  src/components/RichTextEditor.jsx
  src/pages/Home.jsx
  src/pages/Suites.jsx
Labels: bug, enhancement

#22 Hotfixed CSS Changes
  src/components/AddKnowledgeCard.jsx
  src/components/AllKC.jsx
  src/components/KnowledgeCard.jsx
  src/components/RichTextEditor.jsx
  src/pages/Home.jsx
  src/pages/Suites.jsx
Labels: enhancement

#26 Added Copy Card Feature to the Public space so user can copy any public card
  src/components/KnowledgeCard.jsx
  src/services/KnowledgeCardService.js
Labels: feature

#34 added a feature to upload pdf/docx file to create a knowledge card
  src/components/UploadFileForCard.jsx
  src/pages/Home.jsx
Labels: feature
